version: "3.8"

services:
  app:
    build: .
    container_name: esami_pef_app
    ports:
      - "5555:5000"
    volumes:
      - ./:/app
      - ./instance:/app/instance
      - ./backups:/app/backups
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:////app/instance/esami_pef.db
    restart: unless-stopped
