"""Rimuovi ruolo dal modello MembroCommissione

Revision ID: 2a127d04fadf
Revises: 51b1e25224c2
Create Date: 2025-05-28 18:01:00.055733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a127d04fadf'
down_revision = '51b1e25224c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membro_commissione') as batch_op:
        batch_op.drop_column('ruolo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membro_commissione') as batch_op:
        batch_op.add_column(sa.Column('ruolo', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
