"""Aggiunta tabella membro_commissione e relazione con commissione

Revision ID: 51b1e25224c2
Revises: f0dd4fc56f3b
Create Date: 2025-05-28 17:56:04.877445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b1e25224c2'
down_revision = 'f0dd4fc56f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membro_commissione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cognome', sa.String(length=100), nullable=False),
    sa.Column('ruolo', sa.String(length=50), nullable=False),
    sa.Column('profilo', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('commissione', sa.Column('membro_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'commissione', 'membro_commissione', ['membro_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commissione', type_='foreignkey')
    op.drop_column('commissione', 'membro_id')
    op.drop_table('membro_commissione')
    # ### end Alembic commands ###
