"""Aggiunta colonne data_inizio e data_fine alla tabella esame

Revision ID: f0dd4fc56f3b
Revises: 
Create Date: 2025-05-28 14:10:08.164049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0dd4fc56f3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('calendario_esami')  # Rimosso per evitare errore
    op.alter_column('commissione', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.add_column('esame', sa.Column('data_inizio', sa.DateTime(), nullable=True))
    op.add_column('esame', sa.Column('data_fine', sa.DateTime(), nullable=True))
    op.alter_column('esame', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('esame', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('esame', 'data_fine')
    op.drop_column('esame', 'data_inizio')
    op.alter_column('commissione', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_table('calendario_esami',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('esame_id', sa.INTEGER(), nullable=False),
    sa.Column('data_inizio', sa.DATETIME(), nullable=False),
    sa.Column('data_fine', sa.DATETIME(), nullable=False),
    sa.Column('modalita', sa.VARCHAR(length=20), nullable=False),
    sa.Column('sede', sa.VARCHAR(length=200), nullable=True),
    sa.Column('attivita', sa.VARCHAR(length=50), server_default=sa.text("'altro'"), nullable=False),
    sa.ForeignKeyConstraint(['esame_id'], ['esame.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
